#include <jni.h>
#include <stdio.h>
#include "com_jni_Demo.h"  // generated by: javac -h <headersDir> src/main/java/com/jni/Demo.java

// Implementation for: public static native int Demo.add(int a, int b);
JNIEXPORT jint JNICALL Java_com_jni_Demo_add(JNIEnv *env, jclass clazz, jint a, jint b) {
    (void)env;   // unused
    (void)clazz; // unused for static methods
    return a + b;
}
